New: Add aws_customer_gateway
Type of change:
===============
- New feature

What changed? ... and Why:
==========================
Add the ability to codify AWS Customer Gateways.

Also realized that in the case where the existing AWS resources don't
have a `Name` tag, the code I had been using would fail, due to:
```
irb(main):001:0> nil[:foo]
NoMethodError: undefined method `[]' for nil:NilClass
```
So I changed all instances where I could find of tag lookup to:
```
.merge(
  {
    _terraform_id: ...,
    _geo_id: resource[:tags].find { |tag| tag[:key] == "Name" }&.dig(:value)
  }

)
```
Which will return a `nil` geo ID if the `Name` tag does not exist.

How has it been tested:
=======================
The usual tests

@mentions:
==========
@grahamjenson