Fix ArgumentError With Finder
Currently, an invalid extra argument is being passed to `find` method. This
results in the following error:

```
ArgumentError: wrong number of arguments (given 2, expected 1)
```

This adds a test to check for this regression in the future and fixes it.